from __future__ import annotations

import argparse


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="ocr-finetune-train")
    subparsers = parser.add_subparsers(dest="command", required=True)
    probe = subparsers.add_parser("probe")
    probe.add_argument("--json", action="store_true")

    prepare_training = subparsers.add_parser("prepare-training-view")
    prepare_training.add_argument("--upstream", default="/workspace/browser_ocr/finetune/upstream.json")
    prepare_training.add_argument("--paddleocr-root", default="/opt/PaddleOCR")
    prepare_training.add_argument("--manifest", required=True)
    prepare_training.add_argument("--split", required=True)
    prepare_training.add_argument("--output-dir", required=True)
    prepare_training.add_argument("--json", action="store_true")

    prepare_mixed = subparsers.add_parser("prepare-mixed-training-view")
    prepare_mixed.add_argument("--upstream", default="/workspace/browser_ocr/finetune/upstream.json")
    prepare_mixed.add_argument("--paddleocr-root", default="/opt/PaddleOCR")
    prepare_mixed.add_argument("--historical-manifest", required=True)
    prepare_mixed.add_argument("--historical-split", required=True)
    prepare_mixed.add_argument("--unified-manifest", required=True)
    prepare_mixed.add_argument("--unified-export-dir", required=True)
    prepare_mixed.add_argument("--output-dir", required=True)
    prepare_mixed.add_argument("--json", action="store_true")

    smoke = subparsers.add_parser("smoke")
    smoke.add_argument("--upstream", default="/workspace/browser_ocr/finetune/upstream.json")
    smoke.add_argument("--paddleocr-root", default="/opt/PaddleOCR")
    smoke.add_argument("--pretrained-model", required=True)
    smoke.add_argument("--manifest", required=True)
    smoke.add_argument("--export-dir", required=True)
    smoke.add_argument("--run-dir", required=True)
    smoke.add_argument("--expected-group-by", default="drug_family")
    smoke.add_argument("--train-samples", type=int, default=128)
    smoke.add_argument("--val-samples", type=int, default=64)
    smoke.add_argument("--batch-size", type=int, default=16)
    smoke.add_argument("--json", action="store_true")

    baseline = subparsers.add_parser("baseline")
    baseline.add_argument("--upstream", default="/workspace/browser_ocr/finetune/upstream.json")
    baseline.add_argument("--paddleocr-root", default="/opt/PaddleOCR")
    baseline.add_argument("--pretrained-model", required=True)
    baseline.add_argument("--manifest", required=True)
    baseline.add_argument("--export-dir", required=True)
    baseline.add_argument("--run-dir", required=True)
    baseline.add_argument("--expected-group-by", default="drug_family")
    baseline.add_argument("--epochs", type=int, default=10)
    baseline.add_argument("--batch-size", type=int, default=32)
    baseline.add_argument("--learning-rate", type=float, default=0.0005)
    baseline.add_argument("--warmup-epochs", type=int, default=5)
    baseline.add_argument("--json", action="store_true")

    fixed_eval = subparsers.add_parser("fixed-eval")
    fixed_eval.add_argument("--upstream", default="/workspace/browser_ocr/finetune/upstream.json")
    fixed_eval.add_argument("--paddleocr-root", default="/opt/PaddleOCR")
    fixed_eval.add_argument("--baseline-result", required=True)
    fixed_eval.add_argument("--expected-checkpoint-sha256")
    fixed_eval.add_argument("--manifest", required=True)
    fixed_eval.add_argument("--run-dir", required=True)
    fixed_eval.add_argument("--minimum-required-count", type=int, default=32)
    fixed_eval.add_argument("--device", choices=("gpu", "cpu"), default="gpu")
    fixed_eval.add_argument("--json", action="store_true")

    selected = subparsers.add_parser("selected-finetune")
    selected.add_argument("--upstream", default="/workspace/browser_ocr/finetune/upstream.json")
    selected.add_argument("--paddleocr-root", default="/opt/PaddleOCR")
    selected.add_argument("--initial-baseline-result", required=True)
    selected.add_argument("--expected-initial-checkpoint-sha256")
    selected.add_argument("--manifest", required=True)
    selected.add_argument("--export-dir", required=True)
    selected.add_argument("--run-dir", required=True)
    selected.add_argument("--epochs", type=int, default=4)
    selected.add_argument("--batch-size", type=int, default=32)
    selected.add_argument("--learning-rate", type=float, default=0.00005)
    selected.add_argument("--warmup-epochs", type=int, default=1)
    selected.add_argument("--json", action="store_true")

    for name in ("v6-preflight", "v6-train"):
        v6 = subparsers.add_parser(name)
        v6.add_argument("--upstream", default="/workspace/browser_ocr/finetune/upstream.json")
        v6.add_argument("--paddleocr-root", default="/opt/PaddleOCR")
        v6.add_argument(
            "--pretrained-model",
            default="/artifacts/ocr/training/sources/korean_PP-OCRv5_mobile_rec_pretrained.pdparams",
        )
        v6.add_argument("--manifest", required=True)
        v6.add_argument("--export-dir", required=True)
        v6.add_argument("--run-dir", required=True)
        v6.add_argument("--epochs", type=int, default=4)
        v6.add_argument("--batch-size", type=int, default=32)
        v6.add_argument("--learning-rate", type=float, default=0.00005)
        v6.add_argument("--warmup-epochs", type=int, default=1)
        v6.add_argument("--num-workers", type=int, default=2)
        v6.add_argument("--json", action="store_true")
    return parser
